feat: Show more loop tags and fix multisign width
equinor/procosys-webapp-components pull request #18
Opened 2021-10-06 09:49 UTC by jorgenholme96

Only show three loop tags with an option to show all.

Multisign and multiverify only takes the relative width, and doesn't take the whole screen.

2021-10-07 08:37 UTC, Noggling commented
For meg ser dette greit ut men @ErlendLygre får ta en titt på det for sikkerhets skyld ;)

2021-10-07 08:52 UTC, ErlendLygre requested changes

2021-10-07 08:52 UTC, ErlendLygre commented on src/checklist/Checklist.tsx
> +                {!multiSignOrVerifyIsOpen && (
Implement the loop tags section as a separate component - LoopTags.tsx - now that its complexity has increased.

2021-10-07 08:52 UTC, ErlendLygre commented on src/checklist/Checklist.tsx
> +    & button {
Remove this and use the same button style that we use for "Show more details", defined in CheckItem.tsx on line 36. Now that this button layout will be used in multiple places, please create a new button - "ShowMoreButton.tsx" in the components > buttons folder. This generic button should accept a React.Dispatch<React.SetState<boolean>> function as a prop, and toggle the value. 

Replace your button and the button on CheckItem.tsx line 168 with this new button.

2021-10-07 08:52 UTC, ErlendLygre commented on src/checklist/ChecklistMultiSignOrVerify.tsx
>  const Wrapper = styled.div`
This does need to be position: fixed and fullscreen in the MC app. Lets discuss some solutions for this.

<img width="645" alt="Screenshot 2021-10-07 at 10 32 13" src="https://user-images.githubusercontent.com/8993868/136351001-2350590b-1df5-4d72-b7b3-701ba9599485.png">
.

2021-10-07 08:52 UTC, ErlendLygre commented on src/checklist/ChecklistMultiSignOrVerify.tsx
> +            <p id="multiSignVerifyHeader">
Please use a ref for this instead of setting ID.

2021-10-08 09:02 UTC, ErlendLygre commented on src/components/buttons/ShowMoreButton.tsx
> +    handleOnClick: () => void;
change this to toggleShowMore: React.Dispatch<React.SetStateAction<boolean>>

2021-10-12 13:30 UTC, merged